export const listaAgentesOficiais = [
  // ================= REGIONAL LESTE =================
  { nome: "ALCIONE BARBOSA DA CRUZ", regional: "Leste" },
  { nome: "ALEMAZILDA VAZ DOS SANTOS", regional: "Leste" },
  { nome: "ALESSANDRA CAVALCANTI DA SILVA", regional: "Leste" },
  { nome: "ALESSANDRA DE ASSIS", regional: "Leste" },
  { nome: "AMANDA KLIPPEL DE AZEVEDO", regional: "Leste" },
  { nome: "ANA MARIA FERNANDES DE BRITO", regional: "Leste" },
  { nome: "ANTONIA MOREIRA", regional: "Leste" },
  { nome: "AUGUSTO A. DE MIRANDA SANTOS", regional: "Leste" },
  { nome: "CEZINA GONÇALVES DE ALMEIDA", regional: "Leste" },
  { nome: "CLEUDIOMAR ROSA DE MOURA", regional: "Leste" },
  { nome: "DANIEL BERNARDO AGUIAR", regional: "Leste" },
  { nome: "DANILA COSTA ALMEIDA", regional: "Leste" },
  { nome: "DIVINA APARECIDA F. DE OLIVEIRA", regional: "Leste" },
  { nome: "DIVINA PEREIRA", regional: "Leste" },
  { nome: "EDER FREITAS CORREA", regional: "Leste" },
  { nome: "ELAINE CRISTINA G. CIRINO", regional: "Leste" },
  { nome: "ELIANE LEITE PEREIRA", regional: "Leste" },
  { nome: "ELIANE PEDROSA DE JESUS PEREIRA", regional: "Leste" },
  { nome: "ELIZABETH ANTUNES SAMPAIO", regional: "Leste" },
  { nome: "ELVIS FAGNER DE OLIVEIRA", regional: "Leste" },
  { nome: "ÉRICA PRISCILA G. CIRINO", regional: "Leste" },
  { nome: "FABIANE ABADIA MARTINS", regional: "Leste" },
  { nome: "FERNANDA BOTELHO DA SILVA", regional: "Leste" },
  { nome: "GAUDISBETH RODRIGUES DA SILVA", regional: "Leste" },
  { nome: "GILVANI MARIA NUNES", regional: "Leste" },
  { nome: "IZILDA FERNANDES DOS SANTOS", regional: "Leste" },
  { nome: "JAINE MARIA SOARES", regional: "Leste" },
  { nome: "JANE RODRIGUES DE FIGUEIREDO", regional: "Leste" },
  { nome: "JEFFERSON J. NUNES DE MOURA", regional: "Leste" },
  { nome: "JOCILENE PEDROSA BARRETO", regional: "Leste" },
  { nome: "JOICE SILVA DOS SANTOS", regional: "Leste" },
  { nome: "JORCILEY FRANCISCO FERREIRA", regional: "Leste" },
  { nome: "JOSÉ MARIA FERREIRA DE OLIVEIRA", regional: "Leste" },
  { nome: "JOSEFINA FELIX DE SOUZA", regional: "Leste" },
  { nome: "JOZE LUIZA DOS SANTOS BARBOSA", regional: "Leste" },
  { nome: "JULIANA NUNES DE ARAUJO", regional: "Leste" },
  { nome: "LAURA REGINA DIAS MARINHO", regional: "Leste" },
  { nome: "LEONARDO GOMES DA CUNHA", regional: "Leste" },
  { nome: "LETICIA EBERHARD VIEIRA", regional: "Leste" },
  { nome: "LUANA SILVA OLIVEIRA", regional: "Leste" },
  { nome: "LUCAS OLIVEIRA DA SILVA", regional: "Leste" },
  { nome: "LUCIANA CARLA DE OLIVEIRA", regional: "Leste" },
  { nome: "LUCILEIDE GONÇALVES SOUZA", regional: "Leste" },
  { nome: "MAISA VALÉRIA RONDÃO", regional: "Leste" },
  { nome: "MARIA CRISTINA LARA", regional: "Leste" },
  { nome: "MARIA DA GLÓRIA CORREIA", regional: "Leste" },
  { nome: "MARIA DE FÁTIMA PADILHA", regional: "Leste" },
  { nome: "MARIA FERREIRA GOMES", regional: "Leste" },
  { nome: "MARIA REGINA PEREIRA", regional: "Leste" },
  { nome: "MARICELMA MAGALHÃES RAMOS", regional: "Leste" },
  { nome: "MARINETE DOS SANTOS CARVALHO", regional: "Leste" },
  { nome: "MARLY MARTINS LOPES SOARES", regional: "Leste" },
  { nome: "MATHEUS DA SILVA VENANCIO", regional: "Leste" },
  { nome: "MAURICEA MAIA DA SILVA", regional: "Leste" },
  { nome: "NATALIA VANNI", regional: "Leste" },
  { nome: "ODEUZA MARIA DE BARROS", regional: "Leste" },
  { nome: "PATRICIA AUXILIADORA P. A. RIBEIRO", regional: "Leste" },
  { nome: "PATRICIA OLIVEIRA", regional: "Leste" },
  { nome: "RAFAELA DA SILVA POLON", regional: "Leste" },
  { nome: "ROBERTA PEREIRA DE SALES RONDON", regional: "Leste" },
  { nome: "ROSEDELMA M. DE OLIVEIRA", regional: "Leste" },
  { nome: "ROSENIRA DE FREITAS BARBOSA", regional: "Leste" },
  { nome: "SAMIRA MIRANDA AGUIAR", regional: "Leste" },
  { nome: "SANMANDAI BOM DESPACHO", regional: "Leste" },
  { nome: "SARA REGINA ROCHA E SILVA", regional: "Leste" },
  { nome: "SILVANI CORREA CONSTANTINO", regional: "Leste" },
  { nome: "SILVANI FERREIRA DO NASCIMENTO", regional: "Leste" },
  { nome: "SIMÃO LIMA DA SILVA", regional: "Leste" },
  { nome: "SOLANGE DARCI CHINVESLKI", regional: "Leste" },
  { nome: "VICENTINA DOMINGAS DA COSTA", regional: "Leste" },
  { nome: "WESLEY CARDOSO RONDON", regional: "Leste" },

  // ================= REGIONAL NORTE =================
  { nome: "ADRIANA PATURISE ACOSTA", regional: "Norte" },
  { nome: "ANA CARLA APARECIDA DA SILVA", regional: "Norte" },
  { nome: "ANGELA M. FERREIRA DA COSTA", regional: "Norte" },
  { nome: "ARINILZA VENTURA CORREA", regional: "Norte" },
  { nome: "ARLENE APARECIDA FERREIRA REAL", regional: "Norte" },
  { nome: "AURITA MARIA DO CARMO SOUZA", regional: "Norte" },
  { nome: "BEATRIZ DA COSTA SILVA", regional: "Norte" },
  { nome: "BENEDITA CARMIRINA S. OLIVEIRA", regional: "Norte" },
  { nome: "BENEDITA NONATO SAMPAIO", regional: "Norte" },
  { nome: "CARMEM A. HARTMANN", regional: "Norte" },
  { nome: "CLAUDINEY ALVES DA SILVA", regional: "Norte" },
  { nome: "CLEBERSON ARCANJO ARECO", regional: "Norte" },
  { nome: "CLEMENTE AP. NUNES DE ALMEIDA", regional: "Norte" },
  { nome: "CREUZA FERREIRA CRUZ DOS SANTOS", regional: "Norte" },
  { nome: "CRISTINA EVELIN PEREIRA DE SOUZA", regional: "Norte" },
  { nome: "DIANY NEVES OLIVEIRA DA SILVA", regional: "Norte" },
  { nome: "DILVA CONCEICAO DE CAMARGO", regional: "Norte" },
  { nome: "EDENILCE FERREIRA LIRA", regional: "Norte" },
  { nome: "EDINEIDE DOMINGUES DE ALMEIDA", regional: "Norte" },
  { nome: "EDMILSON DE MORAIS", regional: "Norte" },
  { nome: "ELIANA GUIMARÃES DE OLIVEIRA", regional: "Norte" },
  { nome: "ELIANE CRISTINA PINTO DA COSTA", regional: "Norte" },
  { nome: "FERNANDA DA SILVA CARVALHO", regional: "Norte" },
  { nome: "FERNANDO DE A. NUNES", regional: "Norte" },
  { nome: "FLÁVIO SOARES MONTEIRO", regional: "Norte" },
  { nome: "FRANCINE OLIVEIRA COSTA DA SILVA", regional: "Norte" },
  { nome: "FRANCISCA DA SILVA PEREIRA", regional: "Norte" },
  { nome: "GENIVALDO RIBEIRO", regional: "Norte" },
  { nome: "GESSICA CRUZ PEREIRA", regional: "Norte" },
  { nome: "GIZELE FERREIRA DE CASTRO", regional: "Norte" },
  { nome: "GLACE MOREIRA DA SILVA", regional: "Norte" },
  { nome: "GLAZIELE ROSA DA SILVA SOUZA", regional: "Norte" },
  { nome: "IRAMEDES CORREA FORTES", regional: "Norte" },
  { nome: "IRON RODRIGUES COELHO", regional: "Norte" },
  { nome: "IZILDA CHARNOSKI", regional: "Norte" },
  { nome: "JAEL ALBERGUINI DE SOUZA", regional: "Norte" },
  { nome: "JEFSON CARVALHO DE ARRUDA", regional: "Norte" },
  { nome: "JOANETE SILVA OLIVEIRA", regional: "Norte" },
  { nome: "JOANIL PAES DA SILVA", regional: "Norte" },
  { nome: "JOSIANA ARRUDA DOS SANTOS", regional: "Norte" },
  { nome: "JOSUE DE OLIVEIRA SILVA", regional: "Norte" },
  { nome: "JUSCINEIDE DE R. GONZAGA", regional: "Norte" },
  { nome: "JUSSARA LEQUE DA SILVA", regional: "Norte" },
  { nome: "LAURA CRISTINA DA SILVA ARAUJO", regional: "Norte" },
  { nome: "LEUZENIRA J. DOS SANTOS RAMOS", regional: "Norte" },
  { nome: "LIANE DIAS DA CRUZ MAGALHÃES", regional: "Norte" },
  { nome: "LUANA DORANTY DE SOUZA", regional: "Norte" },
  { nome: "LUCIA MAURA GOMES PAIXAO", regional: "Norte" },
  { nome: "LUCIANA RIBEIRO NUNES", regional: "Norte" },
  { nome: "LUIZA ROSA SANTOS PORTELA", regional: "Norte" },
  { nome: "LUZINETE GONCALVES DA SILVA", regional: "Norte" },
  { nome: "MARCIO BENEDITO NEVES REGO", regional: "Norte" },
  { nome: "MARCOS MAGALHÃES A. JESUS", regional: "Norte" },
  { nome: "MARIA DIVINA SILVA ARAUJO QUEIROZ", regional: "Norte" },
  { nome: "MARIA JOSE DA SILVA", regional: "Norte" },
  { nome: "MARIA SILENE DOS SANTOS", regional: "Norte" },
  { nome: "MARLISE REGINA L. M. E SILVA", regional: "Norte" },
  { nome: "NELMA FERREIRA DA COSTA", regional: "Norte" },
  { nome: "NOELLI PIRES GONÇALVES", regional: "Norte" },
  { nome: "NOIZE MARIA GOMES DE ASSIS", regional: "Norte" },
  { nome: "PAMELLA DA SILVA BOAVENTURA", regional: "Norte" },
  { nome: "PAULO CEZAR PEREIRA DA SILVA", regional: "Norte" },
  { nome: "RAFAEL FERNANDO LOUZADA", regional: "Norte" },
  { nome: "ROSANA DA SILVA", regional: "Norte" },
  { nome: "ROSEMAR DE CARVALHO SILVA", regional: "Norte" },
  { nome: "RUBIA LAIZE MARTINS DE LARA", regional: "Norte" },
  { nome: "SANDRIANE DIAS DA SILVA", regional: "Norte" },
  { nome: "SIDINEY DIAS DA SILVA", regional: "Norte" },
  { nome: "SILVANIA SILVA DA COSTA", regional: "Norte" },
  { nome: "SIMONE DA SILVA", regional: "Norte" },
  { nome: "THAINA MARIA DE SOUSA", regional: "Norte" },
  { nome: "TOBIAS BENEDITO DA SILVA E SOUZA", regional: "Norte" },
  { nome: "VALERIA PEREIRA ANTENOR", regional: "Norte" },
  { nome: "VICTOR FLAVIO F. DOS SANTOS", regional: "Norte" },
  { nome: "VILMA DA SILVA", regional: "Norte" },
  { nome: "WANNER PEREIRA DE FREITAS", regional: "Norte" },

  // ================= REGIONAL SUL =================
  { nome: "ALEXANDRA PINHEIRO ORLANDO", regional: "Sul" },
  { nome: "ALLYSSANDRA APARECIDA DE SOUZA", regional: "Sul" },
  { nome: "ANA LUCIA MARQUES DE MISQUITA", regional: "Sul" },
  { nome: "ANADIR AMADEUS DA SILVA", regional: "Sul" },
  { nome: "ÂNGELA MARIA SANTOS ARAÚJO", regional: "Sul" },
  { nome: "ANGELA MEIRA DA SILVA", regional: "Sul" },
  { nome: "ANTONIO RIBEIRO DO NASCIMENTO", regional: "Sul" },
  { nome: "AVAY FERREIRA ALVES", regional: "Sul" },
  { nome: "BENEDITA VERÔNICA PEREIRA", regional: "Sul" },
  { nome: "CELSO RODRIGUES DA SILVA", regional: "Sul" },
  { nome: "CONCEIÇÃO APARECIDA DE OLIVEIRA", regional: "Sul" },
  { nome: "CRISTINO SILVA DO PRADO", regional: "Sul" },
  { nome: "DEVONETE DE CARVALHO LEITE", regional: "Sul" },
  { nome: "DIVINA PAULA DOS REIS", regional: "Sul" },
  { nome: "EDIMILSON SEBASTIÃO DE PAULA", regional: "Sul" },
  { nome: "EDUARDO CÉSAR PEREIRA", regional: "Sul" },
  { nome: "ELIANE ANDRÉIA WAGNER", regional: "Sul" },
  { nome: "ELIANE LEITE MOREIRA DOS REIS", regional: "Sul" },
  { nome: "ELISWELTON RODRIGUES TEIXEIRA", regional: "Sul" },
  { nome: "EVA LUCINEI DA SILVA", regional: "Sul" },
  { nome: "EVANILDE DA SILVA FRANCO", regional: "Sul" },
  { nome: "FLORIZETE VERGILIA DA SILVA", regional: "Sul" },
  { nome: "FRANCIS GOMES DA CRUZ", regional: "Sul" },
  { nome: "FRANCISCA GOMES DE OLIVEIRA", regional: "Sul" },
  { nome: "FRANCISLÂNIA DE FREITAS E SOUZA", regional: "Sul" },
  { nome: "GABRIEL HENRIQUE C. E SILVA", regional: "Sul" },
  { nome: "GEISA ALINE AZEVEDO OLIVEIRA SANTOS", regional: "Sul" },
  { nome: "GENECI MARQUES DE LIMA", regional: "Sul" },
  { nome: "GISELE CRISTINA S.BRITO", regional: "Sul" },
  { nome: "ILDA DA SILVA BORGES", regional: "Sul" },
  { nome: "ISABEL GERALDA CRUZ", regional: "Sul" },
  { nome: "ISES PEREIRA DE ALMEIDA PEIXOTO", regional: "Sul" },
  { nome: "IVANETE MARTINS DA CRUZ", regional: "Sul" },
  { nome: "JAIME PEREIRA SANTANA", regional: "Sul" },
  { nome: "JOÃO VICTOR ROSSI BRANDÃO", regional: "Sul" },
  { nome: "JOÃO VICTTOR FERREIRA PAES DE BARROS", regional: "Sul" },
  { nome: "JONIELSON SOUZA DIAS", regional: "Sul" },
  { nome: "JOSÉ AMARO QUEIROZ DE CAMPOS", regional: "Sul" },
  { nome: "JOSÉ LUCAS MONTEIRO", regional: "Sul" },
  { nome: "JULIANA AMANCIO DOS SANTOS", regional: "Sul" },
  { nome: "KATIA RODRIGUES DE SOUSA", regional: "Sul" },
  { nome: "KAUENE SOUZA DE ARRUDA", regional: "Sul" },
  { nome: "KÊMIA CHRISTHYANNY BARBOSA DA SILVA", regional: "Sul" },
  { nome: "KRISTALEM VASCONCELOS BARBOSA DIAS", regional: "Sul" },
  { nome: "LEANDRO JOSÉ DA SILVA", regional: "Sul" },
  { nome: "LENILMA RODRIGUES DOS SANTOS REGO", regional: "Sul" },
  { nome: "LENIR BARBOSA DA SILVA", regional: "Sul" },
  { nome: "LEOCINEY JOANA GUIMARÃES SILVA", regional: "Sul" },
  { nome: "LEONARDO BARBOSA DE MOURA", regional: "Sul" },
  { nome: "LETICIA BAZZI DO NASCIMENTO BALBUENA", regional: "Sul" },
  { nome: "LÍGIA LUZIA DE MORAES", regional: "Sul" },
  { nome: "LÍVIA PÍNTO DE MORAES SILVA SOUZA", regional: "Sul" },
  { nome: "LUCAS JOSÉ DA SILVA LEITE", regional: "Sul" },
  { nome: "LUCAS LEITE DE MORAIS", regional: "Sul" },
  { nome: "LUZINEI BENEDITA DOS SANTOS", regional: "Sul" },
  { nome: "LUZINEIDE VIEIRA DOS SANTOS", regional: "Sul" },
  { nome: "MARCELLO MONTENEGRO", regional: "Sul" },
  { nome: "MARGARETE FRANZOSI", regional: "Sul" },
  { nome: "MARIA AUXILIADORA BARBOSA", regional: "Sul" },
  { nome: "MARIA COSTA FERREIRA", regional: "Sul" },
  { nome: "MARIA EUNICE RONDON", regional: "Sul" },
  { nome: "MARIA MATILDES PEREIRA DA SILVA", regional: "Sul" },
  { nome: "MARIA NEIDE DE OLIVEIRA", regional: "Sul" },
  { nome: "MARIA VERÔNICA SILVA DOS SANTOS", regional: "Sul" },
  { nome: "MARLENE RIBEIRO DE FREITAS", regional: "Sul" },
  { nome: "MAURO DA SILVA", regional: "Sul" },
  { nome: "MISLENE PEREIRA DA SILVA VEIGA", regional: "Sul" },
  { nome: "NATALIA FERREIRA DUQUE", regional: "Sul" },
  { nome: "NATANAEL MELO MONTEIRO", regional: "Sul" },
  { nome: "NILDA DE FREITAS CAFÉ LISBOA", regional: "Sul" },
  { nome: "PAULO DIAS DA SILVA ROCHA", regional: "Sul" },
  { nome: "ROSÂNGELA BEATRIZ LIMA SANTOS", regional: "Sul" },
  { nome: "ROSÂNGELA LEONORA PEIXOTO", regional: "Sul" },
  { nome: "ROSELEIA DE JESUS PEREIRA", regional: "Sul" },
  { nome: "ROSILDA REGINA GOMES DA SILVA", regional: "Sul" },
  { nome: "SANDRA MARIA SANTOS ARAUJO", regional: "Sul" },
  { nome: "SIDNEI SANTOS DA COSTA", regional: "Sul" },
  { nome: "SOLANGE GONÇALVES DA SILVA", regional: "Sul" },
  { nome: "SUZA NETA DA SILVA SANTOS", regional: "Sul" },
  { nome: "TEREZINHA MARIA DA COSTA", regional: "Sul" },
  { nome: "VALDETE APARECIDA MIRANDA", regional: "Sul" },
  { nome: "VALTEIR JESUS DIAS", regional: "Sul" },
  { nome: "VANIR APARECIDA DA SILVA", regional: "Sul" },
  { nome: "VARLICE M JOSÉ PEREIRA", regional: "Sul" },
  { nome: "VERIDIANA INÊS COIMBRA", regional: "Sul" },
  { nome: "WANDERLEIA SILVA AMORIM DE FRANÇA", regional: "Sul" },
  { nome: "WILSON GONÇALO DE OLIVEIRA JR.", regional: "Sul" },
  { nome: "ZENILDA MENDES DA SILVA", regional: "Sul" },

  // ================= REGIONAL OESTE =================
  { nome: "ADEMIR FERREIRA MOURA", regional: "Oeste" },
  { nome: "ALAN SILVA ALVES", regional: "Oeste" },
  { nome: "ALESSANDRA RIBEIRO DA SILVA FERREIRA", regional: "Oeste" },
  { nome: "ALUZAIR DE S. A SANTOS", regional: "Oeste" },
  { nome: "ANA CLÁUDIA DE SOUZA FOLHA", regional: "Oeste" },
  { nome: "ANA PAULA C. DE PAULA", regional: "Oeste" },
  { nome: "ANDERSON SANTANA MOREIRA", regional: "Oeste" },
  { nome: "APARECIDA CRISTINA F. V. PRAXEDES", regional: "Oeste" },
  { nome: "CARLA REGINA C. RODRIGUES", regional: "Oeste" },
  { nome: "CÉLIA DA CRUZ ALMEIDA", regional: "Oeste" },
  { nome: "CLAUDINETE MARIA DOS SANTOS", regional: "Oeste" },
  { nome: "DEBORA DA SILVA COSTA", regional: "Oeste" },
  { nome: "DELMA SÔNIA DOS SANTOS", regional: "Oeste" },
  { nome: "DULCINÉIA LOPES FRANCISCO", regional: "Oeste" },
  { nome: "EDNA APARECIDA SILVA AGUIAR", regional: "Oeste" },
  { nome: "EDNA MARIA RODRIGUES DA MATA", regional: "Oeste" },
  { nome: "ELIANE PEREIRA BISPO", regional: "Oeste" },
  { nome: "ELIZABET MARIA ALMEIDA", regional: "Oeste" },
  { nome: "EVA LAURA FEITOSA", regional: "Oeste" },
  { nome: "FÁBIO SANTOS EPPINE", regional: "Oeste" },
  { nome: "FRANCISCA N. DE SOUZA BELÉM", regional: "Oeste" },
  { nome: "GEISY KARINE MIRANDA DA SILVA", regional: "Oeste" },
  { nome: "GISELE FRANCISCA DA CRUZ", regional: "Oeste" },
  { nome: "GUILHERME VINICIUS DA SILVA", regional: "Oeste" },
  { nome: "HAYDÊ DOMINGAS DE LIMA", regional: "Oeste" },
  { nome: "HECTOR DA SILVA NASCIMENTO", regional: "Oeste" },
  { nome: "ISAQUE DAMARCO DE SOUZA BORGES", regional: "Oeste" },
  { nome: "IVANETE DO CARMO JUVENAL", regional: "Oeste" },
  { nome: "JANAÍNA PACHECO CUNHA", regional: "Oeste" },
  { nome: "JANETE MARIA DE MORAES", regional: "Oeste" },
  { nome: "JÉSSICA DE SOUZA PEREIRA", regional: "Oeste" },
  { nome: "JOANILDE DA SILVA LEITE", regional: "Oeste" },
  { nome: "JOÃO BATISTA DE PAULA SILVA", regional: "Oeste" },
  { nome: "JOCIEL CARVALHO MAGALHÃES", regional: "Oeste" },
  { nome: "JOCILENE MARIA DA S.E PAULA", regional: "Oeste" },
  { nome: "JOSÉ JAIRO DA SILVA", regional: "Oeste" },
  { nome: "JOSELINE DE SOUZA LEAL", regional: "Oeste" },
  { nome: "JOSIANE DA CRUZ MARQUES", regional: "Oeste" },
  { nome: "JULIETE DE CAMARGO", regional: "Oeste" },
  { nome: "JURANDIR LUIZ DA COSTA JUNIOR", regional: "Oeste" },
  { nome: "JUSTINA R. DO NASCIMENTO", regional: "Oeste" },
  { nome: "KAMILLY VALMARAS S. DE FREITAS", regional: "Oeste" },
  { nome: "KAREN E. DE S. GOMES", regional: "Oeste" },
  { nome: "LEONARDO BRUNO B. CORTEZ", regional: "Oeste" },
  { nome: "LUIS HENRIQUE BARRETO LOPES", regional: "Oeste" },
  { nome: "LUIZ CLÁUDIO VITÓRIO NUNES", regional: "Oeste" },
  { nome: "LUZIA DA SILVA CALDAS", regional: "Oeste" },
  { nome: "MARCIA CRISTINA O. LOPES", regional: "Oeste" },
  { nome: "MARIA EDUARDA DA S. PAULO", regional: "Oeste" },
  { nome: "MICAEL DE SOUZA SILVA", regional: "Oeste" },
  { nome: "MILENA FRAGA DE SOUZA DA ROSA", regional: "Oeste" },
  { nome: "MIRIAN DANTAS DE OLIVEIRA", regional: "Oeste" },
  { nome: "MISPÃ DANTAS DE OLIVEIRA", regional: "Oeste" },
  { nome: "NADJA JAMILLE PEREIRA TAVARES", regional: "Oeste" },
  { nome: "NATASHA MARTINS DE O. SIQUEIRA", regional: "Oeste" },
  { nome: "NATHALIE L. K. DE MORAES SOUSA", regional: "Oeste" },
  { nome: "PATRICIA DE CAMPOS PRADO", regional: "Oeste" },
  { nome: "REGINA LUCIA RONDON", regional: "Oeste" },
  { nome: "ROBERTE ANDERS DE OLIVEIRA ARRUDA", regional: "Oeste" },
  { nome: "ROMILDA DE FARIAS", regional: "Oeste" },
  { nome: "ROSALINO GOMES DE SOUZA JUNIOR", regional: "Oeste" },
  { nome: "SILVANA ROSA E SILVA", regional: "Oeste" },
  { nome: "SOLANGE MARIA CORDEIRO", regional: "Oeste" },
  { nome: "SOLANGE MOURA LIMA", regional: "Oeste" },
  { nome: "SOLANGE REGINA DA SILVA", regional: "Oeste" },
  { nome: "SONEILSON GOMES CORDEIRO", regional: "Oeste" },
  { nome: "SÔNIA DA COSTA ALVES COELHO", regional: "Oeste" },
  { nome: "VALDINEI FERREIRA AMORIM", regional: "Oeste" },
  { nome: "VERA LÚCIA DE CASTRO", regional: "Oeste" },
  { nome: "WANIA VALERIA FERREIRA CALDAS", regional: "Oeste" },
  { nome: "WENDER FABRÍCIO RODRIGUES FERNANDES", regional: "Oeste" },
  { nome: "WILSON APARECIDO CARVALHO CUTAS", regional: "Oeste" }
];