export const tabelaBairros = [
        // ================= REGIONAL LESTE =================
        { nome: "ALPHAVILLE I", regional: "Leste", estrato: "13" },
        { nome: "ALPHAVILLE II", regional: "Leste", estrato: "13" },
        { nome: "AREÃO", regional: "Leste", estrato: "11" },
        { nome: "BANDEIRANTES", regional: "Leste", estrato: "10" },
        { nome: "BARBADO", regional: "Leste", estrato: "09" },
        { nome: "BARRO DURO", regional: "Leste", estrato: "13" },
        { nome: "BEIRA RIO", regional: "Leste", estrato: "09" },
        { nome: "BELA MARINA", regional: "Leste", estrato: "09" },
        { nome: "BELA VISTA", regional: "Leste", estrato: "14" },
        { nome: "BELVEDERE I", regional: "Leste", estrato: "12" },
        { nome: "BELVEDERE II", regional: "Leste", estrato: "12" },
        { nome: "BOA ESPERANÇA", regional: "Leste", estrato: "11" },
        { nome: "BOSQUE DA SAÚDE", regional: "Leste", estrato: "13" },
        { nome: "CACHOEIRA DAS GARÇAS", regional: "Leste", estrato: "11" },
        { nome: "CAMPO VELHO", regional: "Leste", estrato: "09" },
        { nome: "CAMPUS ELÍSEOS", regional: "Leste", estrato: "09" },
        { nome: "CANJICA", regional: "Leste", estrato: "13" },
        { nome: "CARUMBÉ", regional: "Leste", estrato: "14" },
        { nome: "COND. RESERVA RIO CUIABÁ", regional: "Leste", estrato: "12" },
        { nome: "COND. RIO CACHOEIRINHA", regional: "Leste", estrato: "12" },
        { nome: "COND. RIO CLARO", regional: "Leste", estrato: "12" },
        { nome: "COND. RIO COXIPÓ", regional: "Leste", estrato: "12" },
        { nome: "COND. RIO JANGADA", regional: "Leste", estrato: "12" },
        { nome: "COND. RIO MANSO", regional: "Leste", estrato: "12" },
        { nome: "COND. RIO SÃO LOURENÇO", regional: "Leste", estrato: "12" },
        { nome: "DOM AQUINO", regional: "Leste", estrato: "10" },
        { nome: "FLORAIS DO PARQUE", regional: "Leste", estrato: "13" },
        { nome: "FLORAIS ITÁLIA", regional: "Leste", estrato: "13" },
        { nome: "GRANDE TERCEIRO", regional: "Leste", estrato: "09" },
        { nome: "ITAMARATY", regional: "Leste", estrato: "14" },
        { nome: "JARDIM CALIFORNIA", regional: "Leste", estrato: "09" },
        { nome: "JARDIM DAS AMÉRICAS", regional: "Leste", estrato: "11" },
        { nome: "JARDIM DAS AMÉRICAS II", regional: "Leste", estrato: "11" },
        { nome: "JARDIM EUROPA", regional: "Leste", estrato: "09" },
        { nome: "JARDIM GUANABARA", regional: "Leste", estrato: "11" },
        { nome: "JARDIM IMPERIAL I", regional: "Leste", estrato: "12" },
        { nome: "JARDIM IMPERIAL II", regional: "Leste", estrato: "11" },
        { nome: "JARDIM ITÁLIA", regional: "Leste", estrato: "13" },
        { nome: "JARDIM KENNEDY", regional: "Leste", estrato: "09" },
        { nome: "JARDIM LEBLON", regional: "Leste", estrato: "11" },
        { nome: "JARDIM PAULISTA", regional: "Leste", estrato: "10" },
        { nome: "JARDIM PETRÓPOLIS", regional: "Leste", estrato: "09" },
        { nome: "JARDIM RENASCER", regional: "Leste", estrato: "13" },
        { nome: "JARDIM SHANGRILÁ", regional: "Leste", estrato: "09" },
        { nome: "JARDIM TROPICAL", regional: "Leste", estrato: "09" },
        { nome: "JARDIM UNIVERSITÁRIO", regional: "Leste", estrato: "11" },
        { nome: "JARDIM VENEZA", regional: "Leste", estrato: "14" },
        { nome: "LIXEIRA", regional: "Leste", estrato: "10" },
        { nome: "MORADA DOS NOBRES", regional: "Leste", estrato: "13" },
        { nome: "OITO DE ABRIL", regional: "Leste", estrato: "14" },
        { nome: "PEDREGAL", regional: "Leste", estrato: "13" },
        { nome: "PICO DO AMOR", regional: "Leste", estrato: "09" },
        { nome: "PLANALTO", regional: "Leste", estrato: "14" },
        { nome: "POÇÃO", regional: "Leste", estrato: "10" },
        { nome: "PRAEIRINHO", regional: "Leste", estrato: "09" },
        { nome: "PRAEIRO", regional: "Leste", estrato: "09" },
        { nome: "RECANTO DOS PASSÁROS", regional: "Leste", estrato: "12" },
        { nome: "RES. CLAUDIO MARCHETTI", regional: "Leste", estrato: "11" },
        { nome: "RES. MARIA DE LOURDES", regional: "Leste", estrato: "12" },
        { nome: "RES. RECANTO DO SALVADOR", regional: "Leste", estrato: "12" },
        { nome: "RES. SÃO CARLOS", regional: "Leste", estrato: "14" },
        { nome: "RES. J.K", regional: "Leste", estrato: "11" },
        { nome: "SANTA CRUZ I", regional: "Leste", estrato: "12" },
        { nome: "SANTA CRUZ II", regional: "Leste", estrato: "12" },
        { nome: "SANTA INÊS", regional: "Leste", estrato: "14" },
        { nome: "SOL NASCENTE", regional: "Leste", estrato: "14" },
        { nome: "SUPREMO ITÁLIA", regional: "Leste", estrato: "13" },
        { nome: "SÃO MATHEUS", regional: "Leste", estrato: "09" },
        { nome: "SÃO ROQUE", regional: "Leste", estrato: "14" },
        { nome: "TERRA NOVA", regional: "Leste", estrato: "13" },
        { nome: "UFMT", regional: "Leste", estrato: "11" },

        // ================= REGIONAL NORTE =================
        { nome: "1° DE MARÇO", regional: "Norte", estrato: "26" },
        { nome: "ALTOS DA CHAPADA", regional: "Norte", estrato: "21" },
        { nome: "ALTOS DA GLÓRIA", regional: "Norte", estrato: "26" },
        { nome: "ALTOS DA SERRA", regional: "Norte", estrato: "25" },
        { nome: "ALTOS DE CUIABÁ", regional: "Norte", estrato: "21" },
        { nome: "CENTRO AMÉRICA", regional: "Norte", estrato: "22" },
        { nome: "CENTRO POL. ADMINISTRATIVO", regional: "Norte", estrato: "21" },
        { nome: "CHICO MENDES", regional: "Norte", estrato: "21" },
        { nome: "COLINA VERDE", regional: "Norte", estrato: "26" },
        { nome: "COND. BRISAS DA CHAPADA", regional: "Norte", estrato: "21" },
        { nome: "COND. VITÓRIA A", regional: "Norte", estrato: "21" },
        { nome: "COND. VITÓRIA B", regional: "Norte", estrato: "21" },
        { nome: "CPA 1", regional: "Norte", estrato: "22" },
        { nome: "CPA 2", regional: "Norte", estrato: "23" },
        { nome: "CPA 3 SETOR 1", regional: "Norte", estrato: "23" },
        { nome: "CPA 3 SETOR 2", regional: "Norte", estrato: "23" },
        { nome: "CPA 3 SETOR 3", regional: "Norte", estrato: "23" },
        { nome: "CPA 3 SETOR 4", regional: "Norte", estrato: "23" },
        { nome: "CPA 3 SETOR 5", regional: "Norte", estrato: "24" },
        { nome: "CPA 4 - 1° ETAPA", regional: "Norte", estrato: "24" },
        { nome: "CPA 4 - 2° ETAPA", regional: "Norte", estrato: "24" },
        { nome: "CPA 4 - 3° ETAPA", regional: "Norte", estrato: "24" },
        { nome: "CPA 4 - 4° ETAPA", regional: "Norte", estrato: "24" },
        { nome: "CPA 4 - 5° ETAPA", regional: "Norte", estrato: "24" },
        { nome: "DANTE DE OLIVEIRA", regional: "Norte", estrato: "25" },
        { nome: "DR. FABIO 1", regional: "Norte", estrato: "25" },
        { nome: "DR. FABIO 2", regional: "Norte", estrato: "25" },
        { nome: "FLORIANÓPOLIS", regional: "Norte", estrato: "21" },
        { nome: "ITAPUÃ", regional: "Norte", estrato: "21" },
        { nome: "JARDIM BRASIL", regional: "Norte", estrato: "24" },
        { nome: "JARDIM UMUARAMA", regional: "Norte", estrato: "26" },
        { nome: "JARDIM UNIÃO", regional: "Norte", estrato: "21" },
        { nome: "JARDIM VITÓRIA", regional: "Norte", estrato: "21" },
        { nome: "MORADA DO OURO", regional: "Norte", estrato: "22" },
        { nome: "MORADA DO OURO 1° ETAPA", regional: "Norte", estrato: "22" },
        { nome: "MORADA DO OURO 2° ETAPA", regional: "Norte", estrato: "22" },
        { nome: "NOVA CANAÃ 1° ETAPA", regional: "Norte", estrato: "26" },
        { nome: "NOVA CANAÃ 2° ETAPA", regional: "Norte", estrato: "26" },
        { nome: "NOVA CANAÃ 3° ETAPA", regional: "Norte", estrato: "26" },
        { nome: "NOVO HORIZONTE", regional: "Norte", estrato: "24" },
        { nome: "NOVO MATO GROSSO", regional: "Norte", estrato: "23" },
        { nome: "NOVO PARAÍSO 1", regional: "Norte", estrato: "22" },
        { nome: "NOVO PARAÍSO 2", regional: "Norte", estrato: "22" },
        { nome: "PARAISÓPOLIS", regional: "Norte", estrato: "21" },
        { nome: "RES. BOSQUE DOS IPES", regional: "Norte", estrato: "21" },
        { nome: "RES. PAIAGUÁS", regional: "Norte", estrato: "21" },
        { nome: "RES. PARANÁ", regional: "Norte", estrato: "26" },
        { nome: "SILVANOPOLIS", regional: "Norte", estrato: "21" },
        { nome: "TANCREDO NEVES", regional: "Norte", estrato: "22" },
        { nome: "TRÊS BARRAS", regional: "Norte", estrato: "26" },
        { nome: "TRÊS LAGOAS", regional: "Norte", estrato: "24" },
        { nome: "TRÊS PODERES", regional: "Norte", estrato: "21" },
        { nome: "VILA ROSA", regional: "Norte", estrato: "23" },

        // ================= REGIONAL OESTE =================
        { nome: "ALTOS DA BOA VISTA", regional: "Oeste", estrato: "18" },
        { nome: "ALVORADA", regional: "Oeste", estrato: "18" },
        { nome: "ARAÉS", regional: "Oeste", estrato: "17" },
        { nome: "BARRA DO PARI", regional: "Oeste", estrato: "15" },
        { nome: "BORDAS DA CHAPADA I", regional: "Oeste", estrato: "18" },
        { nome: "BORDAS DA CHAPADA II", regional: "Oeste", estrato: "18" },
        { nome: "CANACHUÊ", regional: "Oeste", estrato: "16" },
        { nome: "CAPÃO DO GAMA", regional: "Oeste", estrato: "16" },
        { nome: "CENTRO", regional: "Oeste", estrato: "17" },
        { nome: "CIDADE ALTA", regional: "Oeste", estrato: "16" },
        { nome: "CIDADE VERDE", regional: "Oeste", estrato: "15" },
        { nome: "COESA", regional: "Oeste", estrato: "16" },
        { nome: "COHAB NOVA", regional: "Oeste", estrato: "16" },
        { nome: "COND. COUNTRY", regional: "Oeste", estrato: "19" },
        { nome: "COND. GRAN VILLE", regional: "Oeste", estrato: "19" },
        { nome: "COND. VILA JARDIM", regional: "Oeste", estrato: "19" },
        { nome: "COND. VILAGE DO BOSQUE", regional: "Oeste", estrato: "19" },
        { nome: "CONSIL", regional: "Oeste", estrato: "18" },
        { nome: "COOPHAMIL", regional: "Oeste", estrato: "15" },
        { nome: "DESPRAIADO", regional: "Oeste", estrato: "18" },
        { nome: "DUQUE DE CAXIAS I", regional: "Oeste", estrato: "17" },
        { nome: "DUQUE DE CAXIAS II", regional: "Oeste", estrato: "17" },
        { nome: "FLAMBOYANT", regional: "Oeste", estrato: "16" },
        { nome: "FLORAIS CUIABÁ", regional: "Oeste", estrato: "19" },
        { nome: "FLORAIS DO VALLE", regional: "Oeste", estrato: "19" },
        { nome: "FLORAIS DOS LAGOS", regional: "Oeste", estrato: "19" },
        { nome: "GOIABEIRAS", regional: "Oeste", estrato: "16" },
        { nome: "GUIA", regional: "Oeste", estrato: "20" },
        { nome: "JARDIM AMPERCO", regional: "Oeste", estrato: "18" },
        { nome: "JARDIM ANTARTICA", regional: "Oeste", estrato: "19" },
        { nome: "JARDIM ARAÇÁ", regional: "Oeste", estrato: "15" },
        { nome: "JARDIM BEIRA RIO", regional: "Oeste", estrato: "15" },
        { nome: "JARDIM CUIABÁ", regional: "Oeste", estrato: "16" },
        { nome: "JARDIM ELDORADO", regional: "Oeste", estrato: "18" },
        { nome: "JARDIM INDEPENDÊNCIA", regional: "Oeste", estrato: "16" },
        { nome: "JARDIM MARIANA", regional: "Oeste", estrato: "18" },
        { nome: "JARDIM MONTE LÍBANO I", regional: "Oeste", estrato: "18" },
        { nome: "JARDIM MONTE LÍBANO II", regional: "Oeste", estrato: "18" },
        { nome: "JARDIM NOVO COLORADO", regional: "Oeste", estrato: "19" },
        { nome: "JARDIM PRIMAVERA", regional: "Oeste", estrato: "16" },
        { nome: "JARDIM UBATÃ", regional: "Oeste", estrato: "15" },
        { nome: "JARDIM UBIRAJARA", regional: "Oeste", estrato: "19" },
        { nome: "JARDIM VISTA ALEGRE", regional: "Oeste", estrato: "18" },
        { nome: "JOSÉ PINTO", regional: "Oeste", estrato: "16" },
        { nome: "LIMOEIRO", regional: "Oeste", estrato: "16" },
        { nome: "MIGUEL SUTIL", regional: "Oeste", estrato: "18" },
        { nome: "NOVO TEMPO", regional: "Oeste", estrato: "19" },
        { nome: "NOVO TERCEIRO", regional: "Oeste", estrato: "15" },
        { nome: "PARQUE DAS NAÇÕES INDÍGENAS", regional: "Oeste", estrato: "19" },
        { nome: "PARQUE RODOVIÁRIO", regional: "Oeste", estrato: "18" },
        { nome: "POPULAR", regional: "Oeste", estrato: "17" },
        { nome: "PORTO", regional: "Oeste", estrato: "17" },
        { nome: "QUILOMBO", regional: "Oeste", estrato: "17" },
        { nome: "RANCHO WESTRN", regional: "Oeste", estrato: "19" },
        { nome: "RES. MONTE NEGRO", regional: "Oeste", estrato: "19" },
        { nome: "RES. MÔNACO", regional: "Oeste", estrato: "19" },
        { nome: "RES. SAN MARINO", regional: "Oeste", estrato: "19" },
        { nome: "RES. DESPRAIADO", regional: "Oeste", estrato: "18" },
        { nome: "RES. SUCURI", regional: "Oeste", estrato: "19" },
        { nome: "RIBEIRÃO DA PONTE", regional: "Oeste", estrato: "18" },
        { nome: "RIBEIRÃO DO LIPA", regional: "Oeste", estrato: "19" },
        { nome: "SANTA AMÁLIA", regional: "Oeste", estrato: "15" },
        { nome: "SANTA HELENA", regional: "Oeste", estrato: "17" },
        { nome: "SANTA ISABEL", regional: "Oeste", estrato: "15" },
        { nome: "SANTA MARTA", regional: "Oeste", estrato: "18" },
        { nome: "SANTA ROSA", regional: "Oeste", estrato: "16" },
        { nome: "SENHOR DOS PASSOS", regional: "Oeste", estrato: "18" },
        { nome: "SOLAR DAS FLORES", regional: "Oeste", estrato: "18" },
        { nome: "SUCURI", regional: "Oeste", estrato: "20" },
        { nome: "SÃO BENEDITO", regional: "Oeste", estrato: "15" },
        { nome: "TROPICAL VILLE", regional: "Oeste", estrato: "19" },
        { nome: "VALE DOS LIRIOS", regional: "Oeste", estrato: "19" },
        { nome: "VILA MILITAR", regional: "Oeste", estrato: "16" },
        { nome: "VILA REAL", regional: "Oeste", estrato: "18" },

        // ================= REGIONAL SUL =================
        { nome: "ALTOS DO COXIPÓ", regional: "Sul", estrato: "01" },
        { nome: "ALTOS DO SÃO GONÇALO", regional: "Sul", estrato: "08" },
        { nome: "BRASIL 21 1º ETAPA", regional: "Sul", estrato: "02" },
        { nome: "BRASIL 21 2° ETAPA", regional: "Sul", estrato: "02" },
        { nome: "CHACARA DOS PINHEIROS", regional: "Sul", estrato: "01" },
        { nome: "COHAB SÃO GONÇALO", regional: "Sul", estrato: "07" },
        { nome: "COND. ATHENAS", regional: "Sul", estrato: "02" },
        { nome: "COND. COXIPONÊS", regional: "Sul", estrato: "06" },
        { nome: "COND. FLOR DO CERRADO", regional: "Sul", estrato: "01" },
        { nome: "COND. ILHAS CANÁRIAS", regional: "Sul", estrato: "03" },
        { nome: "COND. ILHEUS", regional: "Sul", estrato: "03" },
        { nome: "COND. JARDIM BOTANICO", regional: "Sul", estrato: "08" },
        { nome: "COND. MORRO DE SANTO ANTONIO", regional: "Sul", estrato: "08" },
        { nome: "COND. NOVO TEMPO - RES. PARK LESTE", regional: "Sul", estrato: "02" },
        { nome: "COND. RES. BELLA PIETRA", regional: "Sul", estrato: "05" },
        { nome: "COND. RES. ESPLANADA", regional: "Sul", estrato: "01" },
        { nome: "COND. SANTA CLARA", regional: "Sul", estrato: "05" },
        { nome: "COND. SANTO ANTONIO", regional: "Sul", estrato: "08" },
        { nome: "COND. SÁVIO BRANDÃO", regional: "Sul", estrato: "07" },
        { nome: "COND. SEVILLA 90-1", regional: "Sul", estrato: "05" },
        { nome: "COND. SEVILLA 90-2", regional: "Sul", estrato: "05" },
        { nome: "COND. VILA BOM JESUS", regional: "Sul", estrato: "02" },
        { nome: "COND. COMPLEXO 300 ANOS (GARÇA BRANCA) A", regional: "Sul", estrato: "07" },
        { nome: "COND. COMPLEXO 300 ANOS (TUIUIU)", regional: "Sul", estrato: "07" },
        { nome: "COND. HAWAI", regional: "Sul", estrato: "04" },
        { nome: "COND. JULIETA 1", regional: "Sul", estrato: "04" },
        { nome: "COND. JULIETA 2", regional: "Sul", estrato: "04" },
        { nome: "COND. VILLAGIO DE PIETRA", regional: "Sul", estrato: "04" },
        { nome: "COOPHEMA", regional: "Sul", estrato: "08" },
        { nome: "COXIPÓ DA PONTE", regional: "Sul", estrato: "01" },
        { nome: "DISTRITO INDUSTRIAL", regional: "Sul", estrato: "06" },
        { nome: "FLOR DE PEQUI", regional: "Sul", estrato: "06" },
        { nome: "GETÚLIO VARGAS", regional: "Sul", estrato: "06" },
        { nome: "IMPÉRIO DO SOL", regional: "Sul", estrato: "04" },
        { nome: "ITAPAJÉ", regional: "Sul", estrato: "06" },
        { nome: "JARDIM ALENCASTRO", regional: "Sul", estrato: "08" },
        { nome: "JARDIM APOEMA", regional: "Sul", estrato: "01" },
        { nome: "JARDIM BURITI", regional: "Sul", estrato: "08" },
        { nome: "JARDIM COMODORO", regional: "Sul", estrato: "08" },
        { nome: "JARDIM DAS FLORES", regional: "Sul", estrato: "04" },
        { nome: "JARDIM DAS OLIVEIRAS", regional: "Sul", estrato: "08" },
        { nome: "JARDIM DAS PALMEIRAS", regional: "Sul", estrato: "01" },
        { nome: "JARDIM DOS IPÊS", regional: "Sul", estrato: "01" },
        { nome: "JARDIM FORTALEZA", regional: "Sul", estrato: "03" },
        { nome: "JARDIM GRAMADO", regional: "Sul", estrato: "08" },
        { nome: "JARDIM HUMAITÁ", regional: "Sul", estrato: "08" },
        { nome: "JARDIM INDUSTRIÁRIO 1", regional: "Sul", estrato: "04" },
        { nome: "JARDIM INDUSTRIÁRIO 2", regional: "Sul", estrato: "04" },
        { nome: "JARDIM LIBERDADE", regional: "Sul", estrato: "03" },
        { nome: "JARDIM MOSSORÓ", regional: "Sul", estrato: "07" },
        { nome: "JARDIM PARAÍSO", regional: "Sul", estrato: "08" },
        { nome: "JARDIM PASSAREDO I", regional: "Sul", estrato: "02" },
        { nome: "JARDIM PASSAREDO II", regional: "Sul", estrato: "02" },
        { nome: "JARDIM PAULICÉIA", regional: "Sul", estrato: "07" },
        { nome: "JARDIM PINHEIROS", regional: "Sul", estrato: "08" },
        { nome: "JARDIM PRESIDENTE 1", regional: "Sul", estrato: "06" },
        { nome: "JARDIM PRESIDENTE 2", regional: "Sul", estrato: "06" },
        { nome: "LAGOA AZUL", regional: "Sul", estrato: "02" },
        { nome: "LOT. DANTE MARTINS DE OLIVEIRA", regional: "Sul", estrato: "05" },
        { nome: "LOT. JD. NOVA VITÓRIA", regional: "Sul", estrato: "05" },
        { nome: "LOT. JARDIM SÃO PAULO", regional: "Sul", estrato: "04" },
        { nome: "LOT. MIRANTE DO PARQUE", regional: "Sul", estrato: "03" },
        { nome: "LOT. SAMPAIO", regional: "Sul", estrato: "05" },
        { nome: "LOT. SANTO EXPEDITO", regional: "Sul", estrato: "05" },
        { nome: "MANDURI", regional: "Sul", estrato: "03" },
        { nome: "NILCE PAES BARRETO", regional: "Sul", estrato: "03" },
        { nome: "NOSSA SENHORA APARECIDA", regional: "Sul", estrato: "08" },
        { nome: "NOSSA SENHORA APARECIDA 2", regional: "Sul", estrato: "08" },
        { nome: "NOVO MILENIUM", regional: "Sul", estrato: "02" },
        { nome: "NOVO PARQUE", regional: "Sul", estrato: "07" },
        { nome: "OSMAR CABRAL", regional: "Sul", estrato: "02" },
        { nome: "PARQUE ATALAIA", regional: "Sul", estrato: "08" },
        { nome: "PARQUE CUIABÁ", regional: "Sul", estrato: "07" },
        { nome: "PARQUE GEORGIA", regional: "Sul", estrato: "08" },
        { nome: "PARQUE MARIANA", regional: "Sul", estrato: "02" },
        { nome: "PARQUE NOVA ESPERANÇA 1", regional: "Sul", estrato: "04" },
        { nome: "PARQUE NOVA ESPERANÇA 2", regional: "Sul", estrato: "04" },
        { nome: "PARQUE NOVA ESPERANÇA 3", regional: "Sul", estrato: "04" },
        { nome: "PARQUE OHARA", regional: "Sul", estrato: "01" },
        { nome: "PARQUE RESIDENCIAL COXIPÓ", regional: "Sul", estrato: "06" },
        { nome: "PASCOAL RAMOS", regional: "Sul", estrato: "03" },
        { nome: "PEDRA 90 1° ETAPA", regional: "Sul", estrato: "05" },
        { nome: "PEDRA 90 2° ETAPA", regional: "Sul", estrato: "05" },
        { nome: "PRIMOR DAS TORRES", regional: "Sul", estrato: "02" },
        { nome: "REAL PARQUE", regional: "Sul", estrato: "07" },
        { nome: "RES. ÁGUAS CLARAS", regional: "Sul", estrato: "04" },
        { nome: "RES. ALICE NOVAK", regional: "Sul", estrato: "04" },
        { nome: "RES. ALTOS DO CERRADO", regional: "Sul", estrato: "03" },
        { nome: "RES. ALTOS DO PARQUE 1", regional: "Sul", estrato: "07" },
        { nome: "RES. ALTOS DO PARQUE 2", regional: "Sul", estrato: "07" },
        { nome: "RES. ARICÁ", regional: "Sul", estrato: "03" },
        { nome: "RES. AVELINO L. BARROS", regional: "Sul", estrato: "03" },
        { nome: "RES. BELITA COSTA MARQUES", regional: "Sul", estrato: "03" },
        { nome: "RES. ESPERANÇA", regional: "Sul", estrato: "08" },
        { nome: "RES. FLOR DE LIZ", regional: "Sul", estrato: "04" },
        { nome: "RES. FRANCISCA L. BORBA", regional: "Sul", estrato: "03" },
        { nome: "RES. JOCKEY CLUB", regional: "Sul", estrato: "07" },
        { nome: "RES. MARECHAL RONDON", regional: "Sul", estrato: "04" },
        { nome: "RES. NICO BARACATE 1", regional: "Sul", estrato: "03" },
        { nome: "RES. NICO BARACATE 2", regional: "Sul", estrato: "03" },
        { nome: "RES. NICO BARACATE 3", regional: "Sul", estrato: "03" },
        { nome: "RES. PASCOAL MOREIRA CABRAL", regional: "Sul", estrato: "04" },
        { nome: "RES. RECANTO DO SOL", regional: "Sul", estrato: "03" },
        { nome: "RES. SALVADOR COSTA MARQUES", regional: "Sul", estrato: "03" },
        { nome: "RES. SONHO MEU", regional: "Sul", estrato: "05" },
        { nome: "RES. SÃO JOSÉ", regional: "Sul", estrato: "06" },
        { nome: "RES. COXIPÓ", regional: "Sul", estrato: "06" },
        { nome: "SANTA LAURA 1", regional: "Sul", estrato: "03" },
        { nome: "SANTA LAURA 2", regional: "Sul", estrato: "03" },
        { nome: "SANTA TEREZINHA 1 SETOR A", regional: "Sul", estrato: "07" },
        { nome: "SANTA TEREZINHA 1 SETOR B", regional: "Sul", estrato: "06" },
        { nome: "SANTA TEREZINHA 1 SETOR C", regional: "Sul", estrato: "06" },
        { nome: "SANTA TEREZINHA 1 SETOR D", regional: "Sul", estrato: "06" },
        { nome: "SANTA TEREZINHA 2 SETOR A", regional: "Sul", estrato: "06" },
        { nome: "SANTA TEREZINHA 2 SETOR B", regional: "Sul", estrato: "06" },
        { nome: "SANTA TEREZINHA 2 SETOR C", regional: "Sul", estrato: "06" },
        { nome: "SANTA TEREZINHA 2 SETOR D", regional: "Sul", estrato: "06" },
        { nome: "SANTA TEREZINHA 2 SETOR E", regional: "Sul", estrato: "06" },
        { nome: "SANTA TEREZINHA 2 SETOR E (1, A 4)", regional: "Sul", estrato: "06" },
        { nome: "SÃO FRANCISCO I", regional: "Sul", estrato: "02" },
        { nome: "SÃO FRANCISCO III", regional: "Sul", estrato: "02" },
        { nome: "SÃO GONÇALO BEIRA RIO", regional: "Sul", estrato: "08" },
        { nome: "SÃO JOÃO DEL REY", regional: "Sul", estrato: "02" },
        { nome: "SÃO JOSÉ", regional: "Sul", estrato: "01" },
        { nome: "SÃO JOSÉ 2", regional: "Sul", estrato: "08" },
        { nome: "SÃO SEBASTIÃO", regional: "Sul", estrato: "03" },
        { nome: "TIJUCAL SETOR I", regional: "Sul", estrato: "01" },
        { nome: "TIJUCAL SETOR II", regional: "Sul", estrato: "01" },
        { nome: "TIJUCAL SETOR III", regional: "Sul", estrato: "01" },
        { nome: "TIJUCAL SETOR IV", regional: "Sul", estrato: "01" },
        { nome: "VILA NOVA", regional: "Sul", estrato: "02" },
        { nome: "VILA VERDE", regional: "Sul", estrato: "06" },
        { nome: "VISTA DA CHAPADA", regional: "Sul", estrato: "04" },
        { nome: "VOLUNTÁRIOS DA PÁTRIA", regional: "Sul", estrato: "05" }
    ];